Make the add-nixbld-users more robust

diff --git a/files/add-nixbld-users b/files/add-nixbld-users
--- a/files/add-nixbld-users
+++ b/files/add-nixbld-users
@@ -3,8 +3,13 @@
 
 set -eu
 
-if [ -z "$1" ] || ! expr "$1" : "[0-9][0-9]*" >/dev/null; then
-	echo "Usage: $0 NUMBER"
+if [ -z "$1" ] || ! expr -- "$1" : "[0-9][0-9]*" >/dev/null; then
+	echo "Usage: $0 NUMBER" 2>/dev/null
+	exit 1
+fi
+
+if [ "$1" -lt 1 ]; then
+	echo "ERROR: NUMBER should be at least 1" 2>/dev/null
 	exit 1
 fi
 
